# EIXO TEMÁTICO 5 – DESENVOLVIMENTO SUSTENTÁVEL NO MEIO RURAL

##  Desenvolvimento sustentável e gestão ambiental de atividades rurais: Conceitos básicos, princípios, objetivos e diretrizes da gestão ambiental e do desenvolvimento sustentável.

###  Campos de interesse e conflitos relacionados à gestão ambiental e ao uso dos recursos naturais

## Licenciamento ambiental de atividades rurais.

### Procedimentos e critérios para o licenciamento ambiental (Resolução Conama nº 237/1997).

## Avaliação de impactos ambientais dos sistemas de produção do campo.

### Critérios básicos e diretrizes gerais para a avaliação de impacto ambiental (Resolução Conama nº 001/1986).

### Mitigação de impactos.

## Gestão ambiental privada de atividades rurais.

## Certificação e Rotulagem de Produtos Agroecológicos.

### Sistemas de certificação orgânica e agroecológica.

### Rastreabilidade e transparência na produção de alimentos.

### Certificação fitossanitária internacional e Certificação fitossanitária de origem (CFO).

### Sistema Unificado de Atenção à Sanidade Agropecuária (Decreto nº 5.741/2006 e alterações), Inspeção industrial e sanitária de produtos de origem animal (Lei nº 1.283/1950 e alterações, Lei nº 7.889/1989 e alterações e Decreto nº 9.013/2017 e alterações).

## Mudança do clima, adaptação e mitigação no meio rural.

### Acordo de Paris sob a Convenção-QUADROS das Nações Unidas sobre Mudança do Clima.

### Política Nacional sobre Mudança do Clima – PNMC (Lei nº 12.187/2009).

### Fundo Nacional sobre Mudança do Clima (Lei nº 12.114/2009 e alterações); soluções baseadas na natureza; ferramentas de adaptação das atividades rurais às mudanças climáticas; mercado de carbono.

## Zoneamento Ecológico‐Econômico, Reforma agrária, Agricultura familiar e comunitária e sustentabilidade.

### Estado e planejamento agrícola no Brasil.

### Programa de Zoneamento Ecológico‐Econômico (concepção geral, fundamentos conceituais e crédito rural).

### Zoneamento Ecológico-Econômico do Brasil – ZEE (Decreto nº 4.297/2002 e alterações).

### Programa Nacional de Zoneamento Agrícola de Risco Climático (Decreto nº 9.841/2019.

## Uso sustentável de recursos naturais e iniciativas produtivas indígenas (Eixo 5 – PNGATI).