project:
  type: book

book:
  title: "Estudos CNU"
  subtitle: "Bloco 3 - Ambiental, Agrária e Biológicas"
  author: "João Frederico Berner"
  date: "1/31/2024"
  chapters:
    - index.qmd
    - 01_politicas-publicas.qmd
    - 02_democracia-cidadania_desafios.qmd
    - 03_etica-integridade.qmd
    - 04_diversidade-sociedade.qmd
    - 05_adm-publica-federal.qmd
    - 06_finanças-publicas.qmd
    - 07_gestao-governamental.qmd
    - 08_politicas-publicas.qmd
    - 09_paisagem-meio-rural.qmd
    - 10_producao-agropecuaria.qmd
    - 11_desenvolvimento-sustentável.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



